### ISSUE TITLE
Not working/No funtion

### ISSUE THREAD

**Issue by MvPts** [ThomasProbyn/FLStudio_APC_Mini_Script#2]
Does this script still work?

I am on v20.7.3 [1987] and there is no sign that this script works. No lit up LEDs. Nothing.

Does ist still work for anyone? Or am I doing something wrong?

**Comment by ThomasProbyn** [comment]
Hi, everything seems to work fine with me. I'm getting light and mixer control on 20.8,with the newest version of the script. Would you be able to tell me what it says in the view>script output window in fl as that could help me get to the bottom of this. If it's working normally, it should say 'init ok'. Having said all this, I wanted to overhaul the script soon anyway to add new functionality.

**Comment by MvPts** [comment]
Thanks for confirming and pointing me in the right direction!

The script output window showed the following message:

> init ok
Traceback (most recent call last):
  File "<string>", line 15, in OnInit
  File "<string>", line 71, in clearAllLEDs
TypeError: Linked device not assigned

I didn't assign Ports for Input/Ouput Midi Devices.

I fixed it by setting both to "Port 1".

Rookie mistake I guess :D

Its working now and I will play around with it today!
Thanks again!
